# Generated by Django 4.2.11 on 2024-06-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='graphic_mode',
            field=models.CharField(default='medium', max_length=10),
        ),
    ]
