# Generated by Django 4.2.11 on 2024-06-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstat',
            name='gameTime',
            field=models.IntegerField(default=0),
        ),
    ]
