FROM nginx:stable-alpine3.17

#Port to listen 
EXPOSE 443

# COPY nginx.conf /etc/nginx/nginx.conf

# # Specify the directory where the application code will be mounted inside the container
# ENV APP_DIR=/usr/share/nginx/html

# # Set the working directory
# WORKDIR $APP_DIR

# # Copy the HTML files to the application directory inside the container
# COPY html /usr/share/nginx/html/.

# # Define a default command to run when the container starts
CMD ["nginx", "-g", "daemon off;"]