# Lastest version of PostgreSQL 
FROM postgres:14-alpine

#Port to listen 
EXPOSE 5432

# Environment variables
ENV POSTGRES_USER=cllovio
ENV POSTGRES_PASSWORD=Coucou-69
ENV POSTGRES_DB=test

#run debug 
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

# CMD ["sleep", "2000"]