
words = [
    "DESK", "CHAIR", "SOFA", "SHELF", "CLOCK", "WATCH", "PHONE", "EMAIL", 
    "RADIO", "MOUSE", "BOARD", "PAPER", "PENCIL", "BOOKS", "NOTES", "FILES", 
    "STUDY", "SCHOOL", "CLASS", "TEACH", "LEARN", "PLANS", "GOALS", "DREAM", 
    "SKILL", "VOICE", "SPEAK", "WRITE", "READS", "COUNT", "INDEX", "CLOUD", 
    "STORM", "RAINY", "SUNNY", "WINDY", "DRIZZ", "SLEET", "SNOWY", "FLOOD", 
    "THUND", "FLASH", "BIRDS", "CRANE", "DUCKS", "EAGLE", "FINCH", "GOOSE", 
    "HERON", "IBIS", "JAY", "KIWI", "LARK", "MIDGE", "NIGHT", "OWL", "PEAF", 
    "QUAIL", "ROBIN", "SWAN", "GOLD", "URIAL", "PINK", "WEAVE", "XENUS", 
    "YEEL", "ZEBRA", "ALGAE", "BAMBO", "CACTU", "DAISY", "ELM", "FERN", 
    "GRASS", "HOLLY", "IRIS", "JUNIP", "KELP", "LILAC", "MAPLE", "NASTU", 
    "OAK", "PALM", "QUEEN", "ROSE", "SEED", "THORN", "GREEN", "RUBY", 
    "WILLO", "RED", "YUCCA", "ZINNI", "ACTOR", "AGENT", "ANGEL"
]

items = [
    "APPLE", "BANANA", "ORANGE", "MOUNTAIN", "RIVER", "OCEAN", "SKY",
    "CLOUD", "STONE", "TREE", "FLOWER", "BREEZE", "SUN", "MOON", "STAR",
    "WORLD", "HOUSE", "GRAPE", "BERRY", "PEACH", "PLUMB", "CHAIR", 
    "TABLE", "WATER", "EARTH", "PLANT", "BLOOM", "SPACE", "LIGHT", 
    "SOUND", "SHINE", "SHADE", "FIELD", "FRUIT", "DRINK", "SMILE", 
    "HAPPY", "GLORY", "PRIDE", "PEACE", "QUIET", "BLISS", "GRACE", 
    "HONOR", "HUMOR", "LAUGH", "GLASS", "PLATE", "SPOON", "KNIFE", 
    "FORCE", "CLEAN", "QUICK", "BRAVE", "BOLD", "CLEAR", "SOLID", 
    "SWEET", "GRAIN", "FLOUR", "BREAD", "TOAST", "BRAND", "LOGIC", 
    "ARRAY", "CODE", "BATCH", "INPUT", "OUTPUT", "VISIT", "MONEY", 
    "PRICE", "VALUE", "POWER", "WIND", "RHYME", "MUSIC", "SONG", 
    "BEACH", "WAVES", "TIDES", "CORAL", "SHORE", "DOCK", "BOATS", 
    "SAILS", "LAKE", "POND", "BROOK", "CREEK", "HILLS", "CLIFF", 
    "RIDGE", "PEAK", "VALLEY", "CAVES", "WOODS"
]

