# Generated by Django 5.0.4 on 2024-04-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
