# Generated by Django 5.0.4 on 2024-04-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
    ]
