# Generated by Django 5.0.4 on 2024-04-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
